date.timezone=UTC
display_errors=On
log_errors=On

; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = -1
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 1024M
; Sets max size of post data allowed.
; http://php.net/post-max-size
post_max_size = 1024M
max_input_vars = 1000
max_execution_time=3600
default_socket_timeout=3600
request_terminate_timeout=600
precision=14
serialize_precision=-1

[xdebug]
zend_extension=xdebug.so
xdebug.idekey = "PHPSTORM"
xdebug.mode=debug
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.client_host=172.17.0.1
xdebug.start_with_request=yes
xdebug.log=/var/www/html/xdebug/xdebug.log
xdebug.discover_client_host=false
xdebug.remote_handler=dbgp
